# Generated by Django 3.1.5 on 2021-01-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=8, unique=True)),
                ('link', models.CharField(max_length=500, unique=True)),
            ],
        ),
    ]
