import { Difficulty } from "./enums/server/Difficulty";
import { Gamemode } from "./enums/server/Gamemode";

export default interface ServerProperties {
  enableJmxMonitoring: boolean;
  rconPort: number;
  levelSeed: string;
  gamemode: Gamemode;
  enableCommandBlock: boolean;
  enableQuery: boolean;
  generatorSettings: string;
  levelName: string;
  motd: string;
  queryPort: number;
  pvp: boolean;
  generateStructures: boolean;
  difficulty: Difficulty;
  networkCompressionThreshold: number;
  maxTickTime: number;
  useNativeTransport: boolean;
  maxPlayers: number;
  onlineMode: boolean;
  enableStatus: boolean;
  allowFlight: boolean;
  broadcastRconToOps: boolean;
  viewDistance: number;
  maxBuildHeight: number;
  serverIp: string;
  allowNether: boolean;
  serverPort: number;
  enableRcon: boolean;
  syncChunkWrites: boolean;
  opPermissionLevel: number;
  preventProxyConnections: boolean;
  resourcePack: string;
  entityBroadcastRangePercentage: number;
  rconPassword: string;
  playerIdleTimeout: number;
  forceGamemode: boolean;
  rateLimit: number;
  hardcore: boolean;
  whiteList: boolean;
  broadcastConsoleToOps: boolean;
  spawnNpcs: boolean;
  spawnAnimals: boolean;
  snooperEnabled: boolean;
  functionPermissionLevel: number;
  levelType: string;
  textFilteringConfig: string;
  spawnMonsters: boolean;
  enforceWhitelist: boolean;
  resourcePackSha1: string;
  spawnProtection: boolean;
  maxWorldSize: number;
}
